### ISSUE TITLE
Risk assessment

### ISSUE THREAD

**Issue by cakemaster9001** [viktorbjerring/Pandekage-tastrofe#10]
Der skal laves en risk assesment af de udarbejdede krav. Formålet med denne risk assesment er, at kunne indele kravene, så det bliver bestemt hvad der er vigtigst at arbejde på i projektet.
For ek skarpelon - se risk assesment fra sidste projekt.

Jonas reviewer

**Comment by mortenhaahr** [comment]
Fra review:
- Første paragraf i risikoanalysen skal omformuleres. Man fatter den ikke
- Bliv bedre til at forklare, hvor tingene kommer fra.
- Eventuelt skriv i caption til figur 5.1, at den er lavet ud fra figur 5.2
