### ISSUE TITLE
BDD

### ISSUE THREAD

**Issue by cakemaster9001** [viktorbjerring/Pandekage-tastrofe#11]
Der skal udarbejdes BDD diagrammer for HW i Pandemix. 
De skal beskrive systemet, så det kan ses hvilke hw enheder der skal udarbejdes og hvordan de hænger sammen. Til BDD diagrammet skal der udarbejdes en signalbeskrivelse, som beskriver de signaler der er i BDD'et

Anton reviewer

**Comment by drunot** [comment]
Jeg har nogle ting, som kan diskuteres. Generelt synes jeg at der godt kunne være flere blokke end hvad der er nødvendigt, også i forhold til hvordan de bliver implementeret.

Her er noget man kunne overveje:
Interface kunne godt bare være en blok

Dej-dispensor: Beholder ventil og dejsensor: er de nødvendige?

PandeMekanik: Evt gøre motor en del af panderne og Temperatur sensor kunne være en del af kogeplade

**Comment by mortenhaahr** [comment]
Note efter review:
- Interface er ikke længere opdelt i WiFi og InternKontrol. Skal have ændret navn til grænseflade.
- Dej-dispenser ingen ændringer.
- Pandemekanik ingen ændringer.

**Comment by mortenhaahr** [comment]
Inout skal markeres med tilde symbol, så man kan se at de er konjugerede.

**Comment by jonashoft** [comment]
Tilføjet funktioner "PandeFri : Digital" og "AktiverPander : Digital"

**Comment by drunot** [comment]
Efter fastslåelse af potokollerne skal PandeFri og DoseringFærdig slåes sammen til en I2C forbindelse. (Hvor dej-dosering er master).

Der er også fortsat en note om at stømforsyningerne skal tilføjes til BBDet.
