### ISSUE TITLE
IBD

### ISSUE THREAD

**Issue by cakemaster9001** [viktorbjerring/Pandekage-tastrofe#12]
Der skal udarbejdes IBDer til Pandemix.
IBDerne skal beskrive de specifikke hw forbindelser i systemet, samt vise specifikationer for forbindelserne. Der skal derudover også laves en signalbeskrivelse til signaler, der viser hvilke protokoller og andre specifikationer der er til signalerne.

Det skal i denne opgave også specificeres hvilke protokoller der benyttes til kommunikation mellem blokkene.

OBS afhægig af BDD

Anton reviewer

**Comment by mortenhaahr** [comment]
Synes nogle af områderne er lidt useriøse. Ex. "Lækker pandekage". Tror ikke vi behøver have et område på dem med dej, men hvis vi har, skal de nok omformuleres lidt. Generelt skal i rette korrekturen igennem:
- Mangel på komma er meget tydelig
- I er ikke konsekvente med stort forbogstav, nogle steder afslutter i med punktum og ikke andre.
- Figurtekst til tabellerne er lidt underlige.

På IBD over dejdispenser står der: "dejpåfyld : dejl" to steder (med et L til sidst)

Har selv rettet nogle stavefejl i Overleaf for jer

**Comment by mortenhaahr** [comment]
Efter review er interface er ikke længere opdelt i WiFi og InternKontrol og den hedder nu grænseflade. I bedes derfor lave samme ændringer.

**Comment by mortenhaahr** [comment]
Fra review af anden gruppe:
- For følgende signaler;  panderotation, varmepande, varmesensor og måske motorkontrol, skal det tydeliggøres, at det er to forskellige signaler. Folk læser det som, at det er samme signal der styrer begge motorer.

**Comment by mortenhaahr** [comment]
- For følgende signaler; panderotation, varmepande, varmesensor og måske motorkontrol, skal det tydeliggøres, at det er to forskellige signaler. Folk læser det som, at det er samme signal der styrer begge motorer.

Ovenstående opgave var løst, men vi var i tvivl efter en snak, om der var en bedre måde. Derfor spørger Mikkel ISE Kim om der er en bedre måde. Lægges over til revideres indtil da.

**Comment by viktorbjerring** [comment]
Der skal også tilføjes et "pande-fri" signal mellem pandesystem og dej-dispenser

**Comment by jonashoft** [comment]
Tilføjet funktioner "PandeFri : Digital" og "AktiverPander : Digital"

**Comment by drunot** [comment]
Pande-Fri mangler på IBD over dispenser. (ikke dej-dispenser), men underblokken dispensor.

**Comment by jonashoft** [comment]
Der skal ændres til at der ikke skal 12V til Arduino Uno, men at der skal spænding til ATmega328p
