### ISSUE TITLE
Domænemodel

### ISSUE THREAD

**Issue by cakemaster9001** [viktorbjerring/Pandekage-tastrofe#13]
Der skal udarbejdes Domænemodel ud fra de udarbejdede usecases. 
Domænemodellen skal beskrive de overordnede domæner, som er i usecasene, samt hvordan disse snakker sammen.
For et ekempel kan man kigge i mappen: 
Vandmarie\Diagrammer\Arkitektur\Applikationsmodel\Billeder\Domaene model
Fra sidste semester.

Oskari reviewer

**Comment by Oskari-Tuormaa** [comment]
* Temperatur sensoren kommer vidst til at sidde på panden, ikke på kogepladen. Desuden bliver kogepladen jo kontrolleret på en eller anden måde, om det så er ved servo eller strømskinne. 
* Jeg ved ikke om det er fordi i bare ikke har "foldet Dej-Dispenser blokken ud", men der mangler også noget omkring nedkøling og regulering af den nedkøling for Dej-Dispenser blokken.
* Jeg kan godt se ideen bag det, men har vi nogle krav eller noget omkring hvorvidt medarbejdere har seperate interfaces? Så vidt jeg har forstået er det vel ikke en del af MVP?

**Comment by Oskari-Tuormaa** [comment]
Sindssygt flot domænemodel! Jeg har kun to kommentare, hvorefter i bare kan smide den direkte til sekundært review:
- Der mangler multiplicitet på kogeplader da vi vel også har to af dem
- Der er en extra ramme omkring diagrammet i overleaf

Good job fellas

**Comment by mortenhaahr** [comment]
Snakkede med Anton om at bytte rundt på API og WiFi. Når dette er udført er den godkendt.
