### ISSUE TITLE
Klassediagrammer

### ISSUE THREAD

**Issue by cakemaster9001** [viktorbjerring/Pandekage-tastrofe#14]
Der skal laves et diagram hvor alle sw klasserne vises.
Denne udarbejdes ud fra domænemodellen.
Klassediagrammet skal vise hvordan de forskellige klasser skal udarbejdes. Det vil sige, at de skal vise hvilke variabler der er tilkoblet klassen, samt hvilke funktioner klassen indeholder.

OBS afhængig af domænemodel

Jonas reviewer

**Comment by viktorbjerring** [comment]
Tilføj forklarende tekst
