### ISSUE TITLE
Sekvensdiagrammer

### ISSUE THREAD

**Issue by cakemaster9001** [viktorbjerring/Pandekage-tastrofe#15]
Der skal laves sekvensdiagrammer ud fra klassediagrammerne.
Sekvensdiagrammerne skal beskrive SW flowet i hver usecase, så det bliver tydeligt hvordan sw sekvensen skal se ud. Sekvensdiagrammerne skal indeholde de korrekte funktionskald, så disse stemmer overens med klassediagrammerne.

OBS afhængig af domænemodel

Jonas reviewer

**Comment by viktorbjerring** [comment]
Tilføj forklarende tekst
