### ISSUE TITLE
Kravspecifikation ikke funktionelle krav

### ISSUE THREAD

**Issue by cakemaster9001** [viktorbjerring/Pandekage-tastrofe#17]
Det skal laves ikke funktionelle krav over systemet.
Disse skal indeles efter MoSCoW.

Viktor og Jesper reviewer

**Comment by mortenhaahr** [comment]
2. Har omformuleret den til "Pandens tilberedningstemperatur skal være over 80\textdegree C", men den er lidt svær at formulere. Vi mente egentlig, at vi skal have en minimumstemperatur, som panden skal blive under tilberedning.
3. Vi tænkte det var relevant for kunden at kunne se, om den er tændt eller slukket.
4. Hvad tænker du vi gør ift. denne? Hvordan vil du uddybe den?
5. Tilføjet krav. Ps. min logik for tallet er som kommentar i Overleaf.
6. Hvad tænkte du her? Det virker som en fin idé, men er det noget vi vil fokusere på?
7. Indført

**Comment by mortenhaahr** [comment]
- Del eventuelt op i kategorier.
- Ikke funktionelle krav skal bedre beskrive reguleringsteknikken. Stil krav til sådan noget som overshoot, delay osv. Både køling og varmelegeme.

**Comment by mortenhaahr** [comment]
Systemet er delt op med FURPS, men det er første gang jeg bruger den, så hold gerne øje med denne, om kategorierne er brugt korrekt.

**Comment by viktorbjerring** [comment]
Hvorfor er halvdelen af FURPS-oversættelsen forklaret?
"Kølingssystemet må maksimalt tage 1 time om at nedkøle dejen." Synes det er en meget bred definition.
"Systemet skal kunne opsættes på enhver lokation, så længe der er adgang til stikkontakter og WiFi" Den lyder enormt farlig, både fra et accepttest-perspektiv og et potentielt forventnings-perspektiv. Hvad hvis jeg vil sætte den op på f.eks. ISS?
