### ISSUE TITLE
Statemachine over UC2 

### ISSUE THREAD

**Issue by viktorbjerring** [viktorbjerring/Pandekage-tastrofe#20]
Anton reviewer

**Comment by Oskari-Tuormaa** [comment]
Statemachinen skal oversættes til dansk og "funktionskaldene" skal gøres mindre kode-agtige.
Skriv et lille stykke brødtekst der forklarer hvorfor statemachinen eksisterer; statemachinen er lavet som et muligt alternativ til UC2
