### ISSUE TITLE
GUI beskrivelse

### ISSUE THREAD

**Issue by viktorbjerring** [viktorbjerring/Pandekage-tastrofe#24]
En beskrivelse af hvordan web-applikationens GUI skal se ud, ideelt som simpelt billede. Flere vinduer der viser forskellige stadier

Anton reviewer

**Comment by mortenhaahr** [comment]
Link til UI: https://xd.adobe.com/view/2127f0f4-b79a-46d6-431c-51a212404881-5716/

**Comment by mortenhaahr** [comment]
GUI beskrivelse lavet - den er at finde i bilagsrapport under kravspec. Kan eventuelt lave billedet i rapporten med færre frames.

**Comment by mortenhaahr** [comment]
Annuller knap skal fjernes

**Comment by mortenhaahr** [comment]
Opdateret så man skal bekræfte sin ordre, og fjernet annullering.
