### ISSUE TITLE
Opdatering af applikationsmodel

### ISSUE THREAD

**Issue by cakemaster9001** [viktorbjerring/Pandekage-tastrofe#35]
Der skal laves en opdatering til applikationsmodellen, så det fremgår at der benyttes 3 microcontrollere.

Den nuværende kan formegentligt benyttes til RPI udviklingen.

Skal ikke reviewes
(review af denne opgave skulle gerne også ske under review af sekvensdiagrammer og klassediagrammer)

**Comment by jonashoft** [comment]
Funktionen wifi.getLevel er blevet ændret til at returnere en int, så den også kan returnere "fejl"

**Comment by jonashoft** [comment]
APPLIKATIONSMODEL GENERELT

Use Case 1:
- UserIF funktion orderCancelled er implementeret direkte i GUI (med HTML) og ikke i Python
- Det med at WiFi har en API giver ikke nogen mening
- ipList skiftet ud med ipDict

Use Case 2:
- waitForOrder fremgår i state machine men ikke sekvensdiagram
- isPancakeDone er ændret til, at den returnerer 0 hvis pandekagen ikke er færdig (eller IP'en ikke har lagt en ordre) og returnerer 1, hvis pandekagen er færdig. Desuden slettes ID'et fra idDict, så man kan lave en ny bestilling.
- Tilføjet en pancakeIsDone til Queue, så den også ved, hvornår den skal fjerne en ordre. Ellers kan den ikke returnere tidsestimat

Use Case 3:
- Lavet helt om til følgende:
Parallel1:
 I2C driver konstant til om BatterController siger, at vi mangler dej:
   Hvis signal modtages
     Skriv "1" til fil

Parallel2:
  Medarbejder tilgår maintenance side.
  Hvis der står "1" i fil:
     Viser rød side om at den mangler dej.
     Knap på siden, som medarbejder kan trykke på for at indikere, at han har fyldt den op.
     Hvis medarbejder trykker på knap:
        2 muligheder:
          1. Python sender signal til I2C driver om, at nu kan den skrive "0" i fil.
          2. Python skriver "0" i fil

  Hvis der står "0" på side:
    Viser side om at alt er OK.


Use Case 4:
- turnOn er sjovt nok ikke implementeret (det er vel et script, der skal ind i en mappe)
- addMsg ikke implementeret, da vi ikke forstod den.
- Vi har et problem. Man kan ikke registrere inde i programmet, om serveren kører som forventet.
- Loopet kan heller ikke implmeneteres af samme årsag...
- Generelt skal hele use case 4 implementeres, eventuelt gennem et bash script eller lignende. Det giver ikke mening at lave det i Python

**Comment by mortenhaahr** [comment]
Skriv forklarende tekst til det hele (punkter fra tidligere Github issues, som nu er lukket)
