### ISSUE TITLE
Overleaf kodeeksempel

### ISSUE THREAD

**Issue by cakemaster9001** [viktorbjerring/Pandekage-tastrofe#4]
Der skal laves et dokument med kodeeksempler i Overleaf. Formålet med dokumentet er at få ens syntaks gruppens medlemmer imellem. Fordelen ved dette er, at vi kan undgå fejl i Overleaf, samt at der bliver struktur i LaTeX koden.

**Comment by drunot** [comment]
Har rettet det til "Kilde kode". Mit problem var bare at alle andre referencer var på dansk og denne ikke var
