### ISSUE TITLE
HW for pandemekanik

### ISSUE THREAD

**Issue by viktorbjerring** [viktorbjerring/Pandekage-tastrofe#41]
Der skal designes og simuleres hardware for blokken PandeMekanik. 
Systemet skal, grundet Covid-19, kun simuleres i første omgang, men så vidt muligt til bedste evne med de inputs der kan forventes. 

Oskari reviewer

**Comment by Oskari-Tuormaa** [comment]
Der står nogle kommentare på linje 73 og 74 der skal tages hånd om

**Comment by Oskari-Tuormaa** [comment]
På linje 74 er den er en meget besynderlig sætning: "da det er ikke til at tage højde for at forhold"

Jeg synes ikke det er så relevant at nævne på linje 140 at det ikke er sikkert at databladdet passer. Det virker bedre hvis det kun bliver diskuteret i konklusionen.

På linje 140 virker det til at der er citeret forkert, da jeg forestiller mig at det er databladet der skal citeres.

Ellers ser det super duper ud :)
