### ISSUE TITLE
API beskrivelse

### ISSUE THREAD

**Issue by cakemaster9001** [viktorbjerring/Pandekage-tastrofe#44]
Der skal laves en API beskrivelse. Denne skal beskrive hvilke funktionskald der er i APIen, så det kan sendes ud til fremtidige kunder. Denne skal beskrive præsis hvad funktionerne gør, så det er nemt at udvikle sin egen server ud fra denne API.

Jonas reviewer

**Comment by mortenhaahr** [comment]
Findes i journaler under 03API -> apibeskrivelse.tex

**Comment by mortenhaahr** [comment]
Lille note: Den beskriver ikke præcis hvad funktionerne gør, da dette ikke bør indgå i en api beskrivelse. Hvordan selve funktionerne på serveren er implementeret, bliver beskrevet under SW for grænseflade i stedet.

Eksempel på en API: https://developer.spotify.com/documentation/web-api/reference/player/
