### ISSUE TITLE
Specificering af krav i kravspek og signalbeskrivelser

### ISSUE THREAD

**Issue by cakemaster9001** [viktorbjerring/Pandekage-tastrofe#49]
Der er nogle værdier der endnu ikke er specificeret i disse dokumenter, da vi manglede viden. Denne viden skal vi til at have. Derfor skal disse undersøges og skrives ind i dokumenterne.

**Comment by mortenhaahr** [comment]
Opgave med at specificere signalbeskrivelser, som også fremgår på scrum boardet, er blevet givet til Oskari og Viktor i stedet, så den ikke bottlenecker. Den del med specificere krav i kravspec er stadig jeres.
