### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by drunot** [viktorbjerring/Pandekage-tastrofe#8]
DOD: Udkast til fully dressed use cases skal være lavet.

Jonas reviewer

**Comment by jonashoft** [comment]
Fully dressed UC3's prækondition giver ikke super meget mening. Menes der at platformen er tændt/klar? 

Hovedscenariet i UC4, punkt 4. Skal der skrives mere om lyset? Like hvor længe skal det blink/hvornår skal det stoppe? Eller skal der beskrives hvorfor den blinker langsomt? Det virker som om at den skal stå og blinke hele tiden, så længe systemet er tændt og har forbindelse, ville det ikke være træls at den står og blinker?
Der mangler også at ordne en \todo, som står ved billedteksten til UC4.

**Comment by mortenhaahr** [comment]
Fra review:
Use cases skal have en aktørbeskrivelse, da der kan forekomme misforståelser med rollerne.

UC1: 
- Initiering skal omformuleres.

UC4:
- Beskriv hvad der sker, hvis den ikke får forbindelse (undtagelsen). Vi forestiller os, at den konstant forsøger.

**Comment by mortenhaahr** [comment]
Genåbnet da der mangler rettelser fra mødet d. 26.03.
Jeg har ikke reviewet endnu

**Comment by jonashoft** [comment]
Jeg synes at der mangler lidt indledende tekst, så man ikke bare får smidt de fire use cases i hovedet og så derefter beskrivelserne.

Ellers ser det fint ud, så hvis i vælger at lave en indledning, så bare ryk den over i done når i er færdige, ellers er den done
