### ISSUE TITLE
Kravspecifikation funktionelle krav

### ISSUE THREAD

**Issue by cakemaster9001** [viktorbjerring/Pandekage-tastrofe#9]
Der skal laves en kravspecifikaiton over Pandemix. 
Der skal udarbjedes nogle funktionelle krav ud fra usecasene.
Kravene skal opdeles efter MoSCoW.

Viktor og Jesper reviewer

**Comment by mortenhaahr** [comment]
De fleste af de ting du skrev er indført. Har tilladt mig at nummere dem.
1. Fjernet håndtere betaling
2. Slettet
3. Indført
4. Indført
5. Det virker ikke interesse mæssigt til, at det er den vej vi ønsker at gå - vi har også mange andre udfordringer i forvejen. Jeg har ladet den stå, men vi kan tage den op på et møde, hvis du brænder for den.
6. Indført som bør krav.

**Comment by mortenhaahr** [comment]
Fra review:
- Mangler et krav om at man kan lægge ordrer i bestilling
- Omformuler afgrænsning, så det bedre forstås hvad vores MVP er. Vi har designet arkitektur + use cases efter should have krav, men MVP indeholder ikke alle de ting.

**Comment by mortenhaahr** [comment]
Afgrænsningen er blevet helt omformuleret, den må reviewer gerne gennemlæse. Det andet fra min tidligere kommentar er også indført.

**Comment by viktorbjerring** [comment]
I afgrænsningen er det beskrevet hvordan at vi ikke er "mekanik-eksperter", men er eksperter i andre ting. Jeg er ikke helt vild med udtrykket eksperter, da det lyder som om at vi laver noget hvori der er intet ukendt stof.
Det er meget fint at beskrive hvordan vi ikke fokuserer på design, men tror det er vigtigt at understrege at der menes visuelt design
Fin note mht pandemien
"Være forbundet til en netværksapplikation"? Menes der webapplikationen eller serveren eller?
